[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12.1", features = ["derive"] }
eframe = { version = "0.19.0", default-features = false, features = [
  "default_fonts",
  "wgpu",
] }
type-map = "0.5.0"
